"""
Generates real, data-backed charts from the actual trained models and a live-scored
sample stream -- used as README images. Not mockups: every number here comes from
running this project's actual code.
"""
import sys
import json
import random
import warnings
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, roc_curve, auc
from sklearn.exceptions import InconsistentVersionWarning

warnings.filterwarnings("ignore", category=UserWarning, module="sklearn")
warnings.filterwarnings("ignore", category=InconsistentVersionWarning)

sys.path.append(str(Path(__file__).resolve().parent.parent / "src"))
from features import UserStateStore, FEATURE_ORDER  # noqa: E402
from risk_engine import score_transaction  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "images"
OUT.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "figure.facecolor": "#0f1117", "axes.facecolor": "#0f1117",
    "savefig.facecolor": "#0f1117", "axes.edgecolor": "#3a3f4b",
    "axes.labelcolor": "#e6e6e6", "xtick.color": "#c7c7c7", "ytick.color": "#c7c7c7",
    "text.color": "#e6e6e6", "grid.color": "#2a2e38", "font.size": 11,
})
ACCENT = "#ff4b6e"
ACCENT2 = "#4bb8ff"
ACCENT3 = "#4bff9f"

xgb_model = joblib.load(ROOT / "models" / "xgb_model.joblib")
iso_model = joblib.load(ROOT / "models" / "iso_forest.joblib")
feat_df = pd.read_parquet(ROOT / "data" / "feature_table.parquet")

from sklearn.model_selection import train_test_split

X = feat_df[FEATURE_ORDER]
y = feat_df["is_fraud"]
# Same split as train.py -- evaluate only on held-out validation data, not the
# rows the model was actually trained on, so this curve honestly reflects
# generalization rather than an optimistic in-sample fit.
_, X_val, _, y_val = train_test_split(X, y, test_size=0.25, stratify=y, random_state=42)

# 1) PR + ROC curves for the supervised model
proba = xgb_model.predict_proba(X_val)[:, 1]
precision, recall, _ = precision_recall_curve(y_val, proba)
fpr, tpr, _ = roc_curve(y_val, proba)
roc_auc = auc(fpr, tpr)

fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
axes[0].plot(recall, precision, color=ACCENT, linewidth=2)
axes[0].set_xlabel("Recall")
axes[0].set_ylabel("Precision")
axes[0].set_title("XGBoost — Precision/Recall Curve")
axes[0].grid(alpha=0.3)

axes[1].plot(fpr, tpr, color=ACCENT2, linewidth=2, label=f"ROC-AUC = {roc_auc:.3f}")
axes[1].plot([0, 1], [0, 1], "--", color="#555", linewidth=1)
axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")
axes[1].set_title("XGBoost — ROC Curve")
axes[1].legend(loc="lower right")
axes[1].grid(alpha=0.3)
plt.tight_layout()
plt.savefig(OUT / "model_performance.png", dpi=140)
plt.close()
print("Saved model_performance.png")

# 2) Feature importance
importances = xgb_model.feature_importances_
order = np.argsort(importances)
fig, ax = plt.subplots(figsize=(8, 5.5))
ax.barh(np.array(FEATURE_ORDER)[order], importances[order], color=ACCENT3)
ax.set_title("XGBoost Feature Importance")
ax.set_xlabel("Importance")
plt.tight_layout()
plt.savefig(OUT / "feature_importance.png", dpi=140)
plt.close()
print("Saved feature_importance.png")

# 3) Simulated live monitor snapshot -- generated by actually running the scoring
#    pipeline over a mixed stream of normal + fraud-burst transactions.
random.seed(7)
store = UserStateStore()
users = [f"U{200000+i}" for i in range(60)]
user_preferred_channel = {u: random.choice(["CARD_PRESENT", "CARD_NOT_PRESENT", "UPI_WALLET", "WIRE_TRANSFER"])
                           for u in users}
t0 = pd.Timestamp("2026-01-01")
main_start = t0 + pd.Timedelta(days=7)  # main demo stream starts a week after warm-up

# Warm up each user with a short history of normal transactions first, so the
# "first transaction ever" cold-start artifact doesn't distort the demo chart --
# in production this is exactly why new-account risk is handled as its own
# rule/segment rather than folded into steady-state anomaly detection.
for user in users:
    warm_ts = t0 + pd.Timedelta(hours=random.uniform(0, 12))
    for _ in range(15):
        warm_ts += pd.Timedelta(hours=random.uniform(2, 20))
        amount = round(max(1, random.gauss(60, 30)), 2)
        channel = user_preferred_channel[user] if random.random() < 0.85 else random.choice(
            ["CARD_PRESENT", "CARD_NOT_PRESENT", "UPI_WALLET", "WIRE_TRANSFER"])
        store.compute_features(user, amount, warm_ts, channel,
                                "IN", f"D{hash(user) % 5000}")

rows = []
idx = 0
for tick in range(220):
    ts = main_start + pd.Timedelta(minutes=tick * 12)  # spread 220 ticks over ~44 hours,
    burst = random.random() < 0.10
    n = random.randint(4, 7) if burst else 1
    for _ in range(n):
        if burst:
            amount = round(random.uniform(0.5, 3.0), 2)
            channel, country, device = "CARD_NOT_PRESENT", random.choice(["NG", "RU"]), f"D_ANOM_{random.randint(1000,9999)}"
            # Separate user pool for fraud targets so a burst doesn't skew a normal
            # user's own running-average baseline for this illustrative chart.
            user = f"FRAUD_TARGET_{random.randint(1, 30)}"
        else:
            user = random.choice(users)
            amount = round(max(1, random.gauss(60, 30)), 2)
            channel = user_preferred_channel[user] if random.random() < 0.85 else random.choice(
                ["CARD_PRESENT", "CARD_NOT_PRESENT", "UPI_WALLET", "WIRE_TRANSFER"])
            country, device = "IN", f"D{hash(user) % 5000}"
        feats = store.compute_features(user, amount, ts, channel, country, device)
        result = score_transaction(feats, xgb_model, iso_model, FEATURE_ORDER)
        rows.append({"idx": idx, "risk": result.fraud_risk_score, "decision": result.decision})
        idx += 1

live_df = pd.DataFrame(rows)
fig, axes = plt.subplots(2, 1, figsize=(10, 6), gridspec_kw={"height_ratios": [2, 1]})
colors = live_df["decision"].map({"ALLOW": ACCENT3, "FLAG": "#ffd24b", "BLOCK": ACCENT})
axes[0].scatter(live_df["idx"], live_df["risk"], c=colors, s=14)
axes[0].axhline(0.80, color=ACCENT, linestyle="--", linewidth=1, label="BLOCK threshold")
axes[0].axhline(0.45, color="#ffd24b", linestyle="--", linewidth=1, label="FLAG threshold")
axes[0].set_ylabel("Fraud risk score")
axes[0].set_title("Live-scored transaction stream (simulated)")
axes[0].legend(loc="upper right", fontsize=9)
axes[0].grid(alpha=0.2)

counts = live_df["decision"].value_counts().reindex(["ALLOW", "FLAG", "BLOCK"]).fillna(0)
axes[1].bar(counts.index, counts.values, color=[ACCENT3, "#ffd24b", ACCENT])
axes[1].set_ylabel("Count")
axes[1].set_title("Decision breakdown")
plt.tight_layout()
plt.savefig(OUT / "live_monitor_snapshot.png", dpi=140)
plt.close()
print("Saved live_monitor_snapshot.png")
print(counts.to_dict())
